/* ELITA-1 audio engine (Tone.js). Signal flow follows Synth1:
   [OSC1 + OSC2 (+sub, ring/sync, FM, noise)] -> mix -> Filter (+filter env) -> Amp (+amp env) -> voice sum
   -> EQ -> Chorus -> Delay -> Pan -> Limiter -> out.   LFO1/2 and the mod envelope modulate pitch / filter / amp / p/w / FM.
   Reads the panel through ELITA.params (Synth1 raw values) and listens to ELITA.onChange. Not meant to be an exact Synth1 copy. */
(function () {
const P = window.ELITA.params, POLY = 6, UNI_MAX = 4; let BPM = 120; const REFV = 0.8;   // unison voices per oscillator are clamped to UNI_MAX (CPU / repeatable timbre)
// LFO type (#42 / #47): 1 = triangle, 2 = pulse (Telephone patch) and 3 = S&H (Computer patch) are confirmed on Synth1; 0 = saw, 4 = sine, 5 = smooth random are unverified.
// 3 and 5 are not oscillator waves: they are generated by a random-value timer (see applyFx)
const LFO_WAVE = ['sawtooth','triangle','square',null,'sine',null];
// Shared wave values (differs from the GUI display order). Confirmed on Synth1:
// osc1 3 = tri; osc2 1 = saw, 2 = pulse, 4 = noise. 0 = sine follows by elimination (osc1 has 4 shapes).
const SUBW = ['sine', 'triangle', 'sawtooth', 'square'];   // #96: 0 sine / 1 triangle (confirmed) / 2 saw / 3 square (the last two follow the Synth1 manual order, unverified)
const OSC1 = ['sine','sawtooth','pulse','triangle'];
const OSC2 = ['sine','sawtooth','pulse','triangle','noise'];
const FTYPE = [['lowpass',-12],['lowpass',-24],['highpass',-12],['bandpass',-12],['lowpass',-24]];
const FTYPE_DUMMY=0;
// Provisional curves (to be tuned by ear)
const time = v => 0.001 * Math.pow(8000, v / 127);   // 1 ms .. 8 s
const CUT_OCT = Math.log2(400);                        // octaves covered by the frequency knob
const cutoff = v => 50 * Math.pow(2, CUT_OCT * v / 127);    // 20 Hz .. 20 kHz

class Voice {
  constructor(out, lfos) {
    this.o1 = new Tone.OmniOscillator({type:'sawtooth'});
    this.o2 = new Tone.OmniOscillator({type:'sawtooth'});
    this.nz = new Tone.Noise('white');
    this.g1 = new Tone.Gain(); this.g2 = new Tone.Gain(); this.gn = new Tone.Gain(0);
    this.f = new Tone.Filter({type:'lowpass', rolloff:-24});
    this.fe = new Tone.FrequencyEnvelope({baseFrequency:200, octaves:4});
    this.amp = new Tone.AmplitudeEnvelope();
    this.o1.connect(this.g1); this.o2.connect(this.g2); this.nz.connect(this.gn);
    [this.g1, this.g2, this.gn].forEach(g => g.connect(this.f));
    this.fe.connect(this.f.frequency);
    this.vg = new Tone.Gain(1);                      // tremolo stage (LFO -> amp)
    // Filter saturation (#23): parallel tanh shaper after the filter, crossfaded with the clean signal
    this.satDry = new Tone.Gain(1); this.satPre = new Tone.Gain(1 / 8); this.satWet = new Tone.Gain(0);
    this.satShaper = new Tone.WaveShaper(x => Math.tanh(8 * x), 2048);          // input is pre-scaled by drive/8, so the output is tanh(drive * x)
    this.f.connect(this.satDry); this.satDry.connect(this.amp);
    this.f.connect(this.satPre); this.satPre.connect(this.satShaper); this.satShaper.connect(this.satWet); this.satWet.connect(this.amp);
    this.amp.connect(this.vg); this.vg.connect(out);
    this.sd = lfos.map(l => { const g = new Tone.Gain(0); l.connect(g); return g; });   // LFO depth sends
    this.dst = [[], []];
    // Sub oscillator: follows OSC1 pitch (0 / -1 oct), no unison
    this.so = new Tone.OmniOscillator({type: 'sine'}); this.sg = new Tone.Gain(0);
    this.so.connect(this.sg); this.sg.connect(this.f); this.so.start();
    // Ring mod: osc1 x osc2 replaces the osc2 signal
    this.mul = new Tone.Multiply(0); this.gr = new Tone.Gain(0);
    this.o1.connect(this.mul); this.o2.connect(this.mul.factor); this.mul.connect(this.gr); this.gr.connect(this.f);
    // Hard sync: worklet slave oscillator restarted by osc1 (stays null if the worklet failed to load)
    this.sy = null; this.sg2 = new Tone.Gain(0); this.sg2.connect(this.f);
    if (SYNC_OK) { this.sy = Tone.getContext().createAudioWorkletNode('sync-osc', {numberOfInputs: 0, outputChannelCount: [1]}); Tone.connect(this.sy, this.sg2); }
    // FM: osc2 acts as the modulator of osc1 pitch (cents)
    this.fm = new Tone.Gain(0); this.o2.connect(this.fm); this.fm.connect(this.o1.detune);
    // Mod envelope: attack -> decay to 0, ignores note-off
    this.me = new Tone.Envelope({attack: 0.001, decay: 0.1, sustain: 0, release: 0.01});
    this.mg = new Tone.Gain(0); this.me.connect(this.mg); this.mt = [];
    [this.o1, this.o2, this.nz].forEach(s => s.start());
    this.on = false; this.note = null; this.t = 0; this.freq = 440; this.midi = 60; this.velF = 1;
  }
  setType(o, t) { if (o.type !== t) o.type = t; }
  trackCut(p) { this.fe.baseFrequency = Math.min(20000, cutoff(p[19]) * Math.pow(2, (this.midi - 60) / 12 * p[22] / 127)); }
  route(g, list, key) {           // reconnect only when the target set changed
    const cur = this[key];
    if (list.length !== cur.length || list.some((t, i) => t !== cur[i])) {
      g.disconnect(); list.forEach(t => g.connect(t)); this[key] = list;
    }
  }
  apply(p) {
    // Unison: fat oscillators (not available for pulse)
    const uni = p[73] ? Math.max(1, Math.min(UNI_MAX, p[93])) : 1, spread = p[75] / 127 * 100;
    const shape = (o, t) => {
      const ty = uni > 1 && t !== 'pulse' ? 'fat' + t : t;
      this.setType(o, ty);
      if (ty.startsWith('fat')) { if (o.count !== uni) o.count = uni; o.spread = spread; }
    };
    shape(this.o1, OSC1[p[0]] || 'sawtooth');
    const t2 = OSC2[p[1]] || 'sawtooth', noise = t2 === 'noise';
    shape(this.o2, noise ? 'sawtooth' : t2);
    const w = -0.9 + 0.9 * p[8] / 127;               // pulse width (right = square)
    [this.o1, this.o2].forEach(o => { if (o.type === 'pulse') o.width.value = w; });
    const m = p[5] / 127 * Math.PI / 2;
    const un = 1 / Math.sqrt(uni);                    // keep level steady with more unison voices
    this.g1.gain.value = Math.cos(m) * 0.5 * un;
    const ring = p[7] && !noise, sync = p[6] && this.sy && !ring && !noise, s2 = Math.sin(m) * 0.5 * un;
    this.g2.gain.value = noise || ring || sync ? 0 : s2;
    this.gr.gain.value = ring ? s2 * un : 0;
    this.sg2.gain.value = sync ? s2 : 0;
    if (this.sy) this.sy.port.postMessage({t: p[1] % 4, w: (-0.9 + 0.9 * p[8] / 127 + 1) / 2});
    this.gn.gain.value = noise ? Math.sin(m) * 0.5 : 0;
    // Sub oscillator (wave values follow OSC1; assumed, unverified). Pulse is a fixed square.
    this.setType(this.so, SUBW[p[96]] || 'sine');          // sub wave numbering differs from OSC1 (1 = triangle confirmed on Synth1 with the Piano patch)
    this.sg.gain.value = p[95] / 127 * 0.5 * Math.cos(m);       // scales with the OSC1 side of the mix
    const [ft, ro] = FTYPE[p[14]] || FTYPE[1];
    this.f.type = ft; if (this.f.rolloff !== ro) this.f.rolloff = ro;
    this.f.Q.value = 0.5 + Math.pow(p[20] / 127, 2) * 9;
    { const sat = p[23] / 127, wet = Math.min(1, sat * 3);                       // 0 = bypass (exactly clean)
      this.satDry.gain.value = 1 - wet; this.satWet.gain.value = wet * 0.5; this.satPre.gain.value = (1 + sat * 14) / 8; }
    this.trackCut(p);
    this.fe.octaves = p[21] / 127 * CUT_OCT * (p[24] ? this.velF : 1);           // #21 amt is unipolar (0 = no envelope): in the 128 factory patches 91 are below 64 and 8 equal 64, so a bipolar reading would close the filter in most patches
    this.fe.attack = time(p[15]); this.fe.decay = time(p[16]);
    this.fe.sustain = p[17] / 127; this.fe.release = time(p[18]);
    this.amp.attack = time(p[25]); this.amp.decay = time(p[26]);
    this.amp.sustain = p[27] / 127; this.amp.release = time(p[28]);
    // LFO routing (shared LFOs; on/dest/depth param numbers)
    let trem = 0;
    const pw = o => o.type === 'pulse' ? [o.width] : [];   // pulse-width signal is recreated when the type changes
    [[57, 41, 44], [58, 46, 49]].forEach(([on, ds, dp], k) => {
      const dest = p[on] ? p[ds] : -1, d = p[dp] / 127;
      const tg = {1: [this.o2.detune], 2: [this.o1.detune, this.o2.detune, this.so.detune], 3: [this.f.detune], 4: [this.vg.gain],
                  5: [...pw(this.o1), ...pw(this.o2)], 6: [this.fm.gain]}[dest] || [];
      if (tg.length !== this.dst[k].length || tg.some((t, i) => t !== this.dst[k][i])) {
        this.sd[k].disconnect(); tg.forEach(t => this.sd[k].connect(t)); this.dst[k] = tg;
      }
      this.sd[k].gain.value = dest < 1 ? 0 : dest <= 2 ? d * 1200 : dest === 3 ? d * 4800
                            : dest === 4 ? d / 2 : dest === 5 ? d * 0.9 : dest === 6 ? d * 2400 : 0;   // cents / cents / gain / width / fm cents
      if (dest === 4) trem += d / 2;
    });
    this.vg.gain.value = 1 - trem;
    // FM depth (provisional curve) and mod envelope routing
    this.fm.gain.value = Math.pow(p[45] / 127, 2) * 4800;
    const on = p[10], amt = (p[11] - 64) / 64, md = p[71];       // amount: 64 = 0
    this.me.attack = time(p[12]); this.me.decay = time(p[13]);
    const mt = !on ? [] : md === 0 ? [this.o2.detune] : md === 1 ? [this.fm.gain] : md === 2 ? [...pw(this.o1), ...pw(this.o2)] : [];
    this.route(this.mg, mt, 'mt');
    this.mg.gain.value = !on ? 0 : md === 0 ? amt * 4800 : md === 1 ? amt * 2400 : md === 2 ? amt * 0.9 : 0;
    this.setPitch(p);
  }
  setPitch(p, glide = 0) {
    const st = Math.max(-24, Math.min(24, p[2] - 64)) + (p[3] - 64) / 100;
    const f2 = this.freq * Math.pow(2, st / 12);
    const set = (sig, f) => glide > 0 ? sig.rampTo(f, glide) : (sig.value = f);
    set(this.o1.frequency, this.freq);
    set(this.so.frequency, this.freq * (p[97] ? 0.5 : 1));
    set(this.o2.frequency, f2);
    if (this.sy) [['f1', this.freq], ['f2', f2]].forEach(([n, f]) => {
      const a = this.sy.parameters.get(n), t = Tone.now();
      a.cancelScheduledValues(t); a.setValueAtTime(a.value, t);
      if (glide > 0) a.linearRampToValueAtTime(f, t + glide); else a.setValueAtTime(f, t);
    });
  }
  down(note, vel, glide = 0, retrig = true) {
    this.midi = note + P[9]; this.note = note; this.on = true; this.t = performance.now();
    this.freq = Tone.Frequency(note + P[9], 'midi').toFrequency();
    this.setPitch(P, glide); this.trackCut(P);
    if (!retrig) return;
    const now = Tone.now(), s = P[30] / 127;
    // velocity (#30 amp sens, #24 filter switch). Relative to the reference velocity REFV (0.8 = PC keys), so a PC-key note sounds the same as before velocity existed.
    this.amp.triggerAttack(now, REFV * (1 - s * (1 - vel)) / (1 - s * (1 - REFV)));          // sens 0 = fixed level, 127 = level follows velocity
    this.velF = Math.max(0, Math.min(1.25, vel / REFV));                                   // #24 on: filter envelope amount follows velocity
    if (P[24]) this.fe.octaves = P[21] / 127 * CUT_OCT * this.velF;
    this.fe.triggerAttack(now); this.me.triggerAttack(now);
  }
  up() {
    this.on = false; this.note = null; this.t = performance.now();
    const now = Tone.now();
    this.amp.triggerRelease(now); this.fe.triggerRelease(now);
  }
}

let shSig = null, lfoOut = null, shTimer = [null, null], lim = null, clip = null, voices = null, master = null, panner = null, eq = null, toneLo = null, toneHi = null, wave = null, lfos = null, chorus = null, chorus2 = null, delay = null;
const LFO_BEATS = [64, 32, 16, 8, 4, 3, 2, 1.5, 1.3333, 1, 0.75, 0.6667, 0.5, 0.375, 0.3333, 0.25, 0.125];   // tempo-sync divisions (beats per LFO cycle), slow -> fast; provisional
let SYNC_OK = false, prevMode = null;
const SYNC_SRC = `class S extends AudioWorkletProcessor {
  static get parameterDescriptors() { return [{name: 'f1', defaultValue: 220, automationRate: 'k-rate'}, {name: 'f2', defaultValue: 220, automationRate: 'k-rate'}]; }
  constructor() { super(); this.a = 0; this.b = 0; this.t = 1; this.w = 0.5; this.port.onmessage = e => { this.t = e.data.t; this.w = e.data.w; }; }
  process(i, o, p) {
    const out = o[0][0], f1 = p.f1[0] / sampleRate, f2 = p.f2[0] / sampleRate;
    for (let n = 0; n < out.length; n++) {
      this.a += f1; if (this.a >= 1) { this.a -= 1; this.b = f1 > 0 ? this.a * f2 / f1 : 0; }   // master wrap resets the slave
      this.b += f2; if (this.b >= 1) this.b -= 1;
      const x = this.b;
      out[n] = this.t === 0 ? Math.sin(6.2832 * x) : this.t === 1 ? 2 * x - 1 : this.t === 2 ? (x < this.w ? 1 : -1) : 4 * Math.abs(x - 0.5) - 1;
    }
    return true;
  }
}
registerProcessor('sync-osc', S);`;

async function initAudio() {
  try {
    await Tone.getContext().addAudioWorkletModule(URL.createObjectURL(new Blob([SYNC_SRC], {type: 'text/javascript'})));
    SYNC_OK = true;
  } catch (e) { console.warn('hard sync unavailable', e); }
  master = new Tone.Gain(0);
  eq = new Tone.Filter({type: 'peaking', frequency: 1000, Q: 1, gain: 0}); panner = new Tone.Panner(0);
  wave = new Tone.Waveform(2048);
  lfos = [0, 1].map(() => new Tone.LFO({min: -1, max: 1}).start());
  shSig = [0, 1].map(() => new Tone.Signal(0));                 // S&H / random LFO value (set by a timer)
  lfoOut = lfos.map((l, k) => { const g = new Tone.Gain(1); l.connect(g); shSig[k].connect(g); return g; });
  chorus = new Tone.Chorus({spread: 180}).start();
  chorus2 = new Tone.Chorus({spread: 180}).start();   // 2nd stage, only used for x3 / x4
  delay = makeDelay();
  lim = new Tone.Limiter(-2); clip = new Tone.WaveShaper(x => Math.tanh(x * 1.2) / 1.2, 2048);
  toneLo = new Tone.Filter({type: 'lowshelf', frequency: 300, gain: 0}); toneHi = new Tone.Filter({type: 'highshelf', frequency: 3000, gain: 0});
  master.chain(eq, toneLo, toneHi, chorus, chorus2, delay.input);
  delay.output.chain(panner, lim, clip, Tone.getDestination());
  clip.connect(wave);
  voices = Array.from({length: POLY}, () => new Voice(master, lfoOut));
  applyAll();
}

// Stereo delay with 3 types (#82: 0 = ST: L/R in parallel, 1 = X: feedback crosses L<->R, 2 = PP: mono in, ping-pong) -- numbering is a guess.
// #83 spread offsets the R delay time, #98 tone darkens the feedback path (0 = no filtering, so ver105 patches that lack it are unchanged).
function makeDelay() {
  const G = v => new Tone.Gain(v), D = () => new Tone.Delay(0.25, 2);
  const d = {input: G(1), output: G(1), dry: G(1), wet: G(0), split: new Tone.Split(2), merge: new Tone.Merge(),
    dl: D(), dr: D(), lpL: new Tone.Filter(20000, 'lowpass'), lpR: new Tone.Filter(20000, 'lowpass'),
    iLL: G(1), iRL: G(0), iLR: G(0), iRR: G(1), fLL: G(0), fLR: G(0), fRL: G(0), fRR: G(0)};
  d.input.connect(d.dry); d.dry.connect(d.output);
  d.input.connect(d.split);
  d.split.connect(d.iLL, 0); d.split.connect(d.iLR, 0); d.split.connect(d.iRL, 1); d.split.connect(d.iRR, 1);
  d.iLL.connect(d.dl); d.iRL.connect(d.dl); d.iLR.connect(d.dr); d.iRR.connect(d.dr);
  d.dl.connect(d.lpL); d.dr.connect(d.lpR);
  d.lpL.connect(d.fLL); d.lpL.connect(d.fLR); d.lpR.connect(d.fRL); d.lpR.connect(d.fRR);
  d.fLL.connect(d.dl); d.fRL.connect(d.dl); d.fLR.connect(d.dr); d.fRR.connect(d.dr);   // f<from><to> naming is by output side: fLL = L->L, fLR = L->R, fRL = R->L, fRR = R->R
  d.lpL.connect(d.merge, 0, 0); d.lpR.connect(d.merge, 0, 1);
  d.merge.connect(d.wet); d.wet.connect(d.output);
  return d;
}
function applyDelay(p) {
  const d = delay, ty = p[82] | 0, fb = Math.min(0.9, p[36] / 127 * 0.9), t = Math.min(2, (p[35] + 1) * 60 / BPM / 16);
  const sp = p[83] / 127;
  d.dl.delayTime.value = t; d.dr.delayTime.value = Math.min(2, t * (1 + sp * 0.5));
  const cross = ty === 1 || ty === 2, mono = ty === 2;
  d.iLL.gain.value = mono ? 0.5 : 1; d.iRL.gain.value = mono ? 0.5 : 0; d.iLR.gain.value = 0; d.iRR.gain.value = mono ? 0 : 1;
  d.fLL.gain.value = cross ? 0 : fb; d.fRR.gain.value = cross ? 0 : fb;
  d.fLR.gain.value = cross ? fb : 0; d.fRL.gain.value = cross ? fb : 0;
  const hz = 20000 * Math.pow(1500 / 20000, p[98] / 127);      // tone 0 = open, 127 = ~1.5 kHz damping (provisional)
  d.lpL.frequency.value = hz; d.lpR.frequency.value = hz;
  const w = p[65] ? p[37] / 127 : 0;
  d.dry.gain.value = Math.cos(w * Math.PI / 2); d.wet.gain.value = Math.sin(w * Math.PI / 2) * 1.2;
  d.wetAmt = w; d.time = t; d.fb = fb; d.type = ty;
}
// Provisional curves for the shared blocks (LFO speed, delay, chorus)
function applyFx(p) {
  master.gain.rampTo(p[29] / 127 * Math.pow(p.vol / 127, 2) * 0.9, 0.02);
  eq.frequency.value = 100 * Math.pow(100, p[61] / 127);          // 100 Hz .. 10 kHz (provisional)
  eq.gain.value = (p[62] - 64) / 64 * 12; eq.Q.value = 0.3 + p[63] / 127 * 6;
  const tn = (p[60] - 64) / 64 * 9;                                 // #60 tone: 64 = flat, up = brighter (highs +, lows -), down = darker; max about ±9 dB each side (provisional)
  toneLo.gain.value = -tn; toneHi.gain.value = tn;
  panner.pan.value = Math.max(-1, Math.min(1, (p[90] - 64) / 63));
  [[42, 43], [47, 48]].forEach(([t, sp], k) => {
    const sync = p[[67, 69][k]];                                // tempo sync: the speed knob picks a beat division instead of a rate
    const hz = sync ? 1 / (LFO_BEATS[Math.round(p[sp] / 127 * 16)] * 60 / BPM) : 0.1 * Math.pow(200, p[sp] / 127);   // free: 0.1 .. 20 Hz
    const ty = p[t], rnd = ty === 3 || ty === 5;
    lfos[k].frequency.value = hz;
    if (rnd) {                                              // 3 = S&H (stepped), 5 = smooth random (glides to each new value)
      if (lfos[k].state === 'started') lfos[k].stop();
      if (shTimer[k] === null || shTimer[k].hz !== hz || shTimer[k].ty !== ty) {
        if (shTimer[k]) clearInterval(shTimer[k].id);
        const f = () => { const v = Math.random() * 2 - 1; if (ty === 5) shSig[k].rampTo(v, 1 / hz); else shSig[k].value = v; };
        f(); shTimer[k] = {hz, ty, id: setInterval(f, 1000 / hz)};
      }
    } else {
      if (shTimer[k]) { clearInterval(shTimer[k].id); shTimer[k] = null; shSig[k].value = 0; }
      lfos[k].type = LFO_WAVE[ty] || 'sine';
      if (lfos[k].state !== 'started') lfos[k].start();
    }
  });
  applyDelay(p);
  chorus.delayTime = 2 + p[52] / 127 * 8;                            // ms
  chorus.depth = p[53] / 127;
  chorus.frequency.value = 0.1 + Math.pow(p[54] / 127, 2) * 8;
  chorus.feedback.value = Math.max(0, p[55] - 64) / 63 * 0.9;        // 64 = 0
  chorus.wet.value = p[66] ? p[56] / 127 : 0;
  // Chorus type: indicator "xN" = value N (Oldage Leader x2, Pain Leader x4). Approximation:
  // x1 = mono LFO, x2 = L/R opposite phase, x3/x4 = extra detuned 2nd stage in series.
  const n = Math.max(1, Math.min(4, p[64]));
  chorus.spread = n === 1 ? 0 : 180;
  chorus2.delayTime = (2 + p[52] / 127 * 8) * 1.3;
  chorus2.depth = p[53] / 127 * 0.8;
  chorus2.frequency.value = chorus.frequency.value * 1.37;
  chorus2.feedback.value = 0;
  chorus2.wet.value = p[66] && n >= 3 ? p[56] / 127 * (n === 4 ? 0.8 : 0.5) : 0;
}
let prevArp = false;
function applyAll() {
  dbgParams();
  if (P[38] !== prevMode) { prevMode = P[38]; allOff(); }
  if (!!P[59] !== prevArp) { prevArp = !!P[59]; arp.held.length = 0; arpStop(); allOff(); }   // switching the arpeggiator releases held notes   // release everything when the play mode changes
  applyFx(P); voices.forEach(v => v.apply(P));
}

// Poly: oldest released voice first, else steal the oldest held one.
// Mono / legato (#38 = 1 / 2): voice 0 only, last-note priority; legato keeps the envelopes running while notes overlap.
const stack = [];
const isMono = () => P[38] === 1 || P[38] === 2;
const glideTime = overlap => (!P[74] || overlap) ? Math.pow(P[39] / 127, 2) * 2 : 0;   // #74 auto: glide only when notes overlap
function allOff() { stack.length = 0; if (typeof arp !== 'undefined') { arp.held.length = 0; clearTimeout(arp.timer); clearTimeout(arp.gateT); arp.timer = arp.gateT = arp.cur = null; } voices.forEach(v => v.on && v.up()); }
// key sync (#68 / #70): restart the LFO phase (or draw a new S&H value) on each note-on
function keySync() {
  [68, 70].forEach((no, k) => {
    if (!P[no] || !P[[57, 58][k]]) return;
    const ty = P[[42, 47][k]];
    if (ty === 3 || ty === 5) { shSig[k].value = Math.random() * 2 - 1; return; }
    if (lfos[k].state === 'started') { const t = Tone.now(); lfos[k].stop(t); lfos[k].start(t + 0.001); }
  });
}
function voiceOn(n, vel = 0.8) {
  if (!voices) return;
  keySync();
  dbgNote('on', n);
  if (isMono()) {
    if (stack.includes(n)) return;
    const overlap = stack.length > 0;
    stack.push(n);
    voices[0].down(n, vel, glideTime(overlap), !(overlap && P[38] === 2));
    return;
  }
  if (voices.some(v => v.note === n)) return;
  const byAge = (a, b) => a.t - b.t;
  const pool = voices.slice(0, Math.max(1, Math.min(POLY, P[94] || POLY)));
  const v = pool.filter(x => !x.on).sort(byAge)[0] || pool.slice().sort(byAge)[0];
  v.down(n, vel);
}
function voiceOff(n) {
  if (!voices) return;
  dbgNote('off', n);
  if (isMono()) {
    const i = stack.indexOf(n);
    if (i < 0) return;
    const last = i === stack.length - 1;
    stack.splice(i, 1);
    if (!last) return;
    if (stack.length) voices[0].down(stack[stack.length - 1], 0.8, glideTime(true), P[38] === 1);
    else voices[0].up();
    return;
  }
  voices.filter(v => v.note === n).forEach(v => v.up());
}

// ---- Arpeggiator (#59 on, #31 type, #32 oct range, #33 beat, #34 gate) ----
// While ON, held keys are not played directly: they are stepped through at the beat rate (follows the BPM box).
// type (#31, 1..4 in the factory files): 1 up, 2 down, 3 up/down, 4 random -- the numbering is a guess (the 128 factory patches use 1 almost everywhere).
// oct range #32: 0..3 = 1..4 octaves.  beat #33: 0..18 index (11 = 1/16), values above 18 are scaled down; table is provisional.
// gate #34: note length as a fraction of the step (value / 127).  No latch: releasing every key stops the arpeggio.
const ARP_BEATS = [4, 3, 2, 1.5, 1.3333, 1, 0.75, 0.6667, 0.5, 0.375, 0.3333, 0.25, 0.1875, 0.1667, 0.125, 0.09375, 0.08333, 0.0625, 0.04167];   // quarter-note beats per step, slow -> fast
const arp = {held: [], i: 0, dir: 1, timer: null, gateT: null, cur: null};
function arpList() {
  const base = arp.held.slice().sort((a, b) => a - b), oct = Math.max(0, Math.min(3, P[32] | 0)), all = [];
  for (let o = 0; o <= oct; o++) base.forEach(n => n + o * 12 <= 127 && all.push(n + o * 12));
  return all;
}
function arpStepSec() { const v = P[33], i = v > 18 ? Math.round(v / 127 * 18) : Math.max(0, v | 0); return ARP_BEATS[i] * 60 / BPM; }
function arpStop() {
  clearTimeout(arp.timer); clearTimeout(arp.gateT); arp.timer = arp.gateT = null;
  if (arp.cur !== null) { voiceOff(arp.cur); arp.cur = null; }
  arp.i = 0; arp.dir = 1;
}
function arpStep() {
  arp.timer = null;
  if (!arp.held.length || !P[59]) return arpStop();
  const l = arpList(), ty = P[31] | 0, n = l.length;
  let k;
  if (ty === 4) k = Math.floor(Math.random() * n);
  else if (ty === 2) { arp.i = (arp.i % n + n) % n; k = n - 1 - arp.i; arp.i++; }
  else if (ty === 3 && n > 1) { if (arp.i >= n - 1) arp.dir = -1; else if (arp.i <= 0) arp.dir = 1; arp.i = Math.max(0, Math.min(n - 1, arp.i)); k = arp.i; arp.i += arp.dir; }
  else { arp.i = arp.i % n; k = arp.i; arp.i++; }
  if (arp.cur !== null) voiceOff(arp.cur);
  arp.cur = l[k]; voiceOn(arp.cur, 0.8);
  const step = arpStepSec(), note = arp.cur;
  clearTimeout(arp.gateT);
  arp.gateT = setTimeout(() => { if (arp.cur === note) { voiceOff(note); arp.cur = null; } }, Math.max(0.01, step * Math.max(0.05, Math.min(1, P[34] / 127))) * 1000);
  arp.timer = setTimeout(arpStep, step * 1000);
}
function noteOn(n, vel = 0.8) {
  if (!voices) return;
  if (!P[59]) return voiceOn(n, vel);
  if (arp.held.includes(n)) return;
  arp.held.push(n);
  dbgNote('on', n);
  if (arp.timer === null) arp.timer = setTimeout(arpStep, 20);   // short wait so the other notes of a chord are in the list before the first step
}
function noteOff(n) {
  if (!voices) return;
  const i = arp.held.indexOf(n);
  if (i >= 0) { arp.held.splice(i, 1); if (!arp.held.length) arpStop(); return; }
  voiceOff(n);
}


// ================= debug mode =================
// Enable:  open the page with ?debug  (or #debug), or run  ELITA.debug.on()  in the console.  Disable: ELITA.debug.off()
// Console helpers:  ELITA.debug.graph()   signal path of the whole synth (voice + effect chain)
//                   ELITA.debug.voice(i)  one voice in detail      ELITA.debug.meters()  level (dB) at each stage
//                   ELITA.debug.params()  params that differ from the defaults, and whether the engine uses them
//                   ELITA.debug.unused()  Synth1 parameters the engine ignores
let DBG = false, lastP = {}, meters = null;
const C = 'color:#fff;background:#c33;padding:0 4px;border-radius:2px', C2 = 'color:#c33;font-weight:bold';
const nm = no => (window.ELITA.names && window.ELITA.names[no]) || '';
const r3 = x => typeof x === 'number' ? +x.toFixed(3) : x;
const NOTE = n => ['C','C#','D','D#','E','F','F#','G','G#','A','A#','B'][n % 12] + (Math.floor(n / 12) - 1);
function usedSet() {   // Synth1 numbers the engine reads, found by scanning the engine source itself
  const src = [Voice.prototype.apply, Voice.prototype.setPitch, Voice.prototype.down, Voice.prototype.trackCut, applyFx, applyDelay, keySync, applyAll, voiceOn, voiceOff, noteOn, noteOff, arpStep, arpList, arpStepSec, glideTime, isMono].map(f => f.toString()).join('\n');
  const u = new Set(); for (const m of src.matchAll(/\b[pP]\[(\d+)\]/g)) u.add(+m[1]);
  [41, 42, 43, 44, 46, 47, 48, 49, 57, 58, 67, 68, 69, 70].forEach(n => u.add(n));   // LFO params are read through index tables
  return u;
}
function dbgParams() {
  if (!DBG) return;
  const ch = [];
  Object.keys(P).forEach(no => { if (P[no] !== lastP[no]) { if (lastP[no] !== undefined) ch.push([no, lastP[no], P[no]]); lastP[no] = P[no]; } });
  if (!ch.length) return;
  if (ch.length > 12) console.log('%c[ELITA]%c patch/preset: %d params changed → engine re-applied (ELITA.debug.graph() to see the path)', C, '', ch.length);
  else ch.forEach(([no, a, b]) => console.log('%c[ELITA]%c #%s %s: %s → %s  %s', C, '', no, nm(no), a, b, usedSet().has(+no) || no === 'vol' ? '' : '(not used by the engine)'));
}
function dbgNote(kind, n) {
  if (!DBG) return;
  if (kind === 'off') { const v = voices.filter(x => x.note === n); console.log('%c[ELITA]%c note OFF %s (%d) → release voice %s', C, '', NOTE(n), n, v.map(x => voices.indexOf(x)).join(',') || '(none)'); return; }
  const mono = isMono();
  setTimeout(() => {   // after allocation
    const v = voices.filter(x => x.note === n);
    const vi = v.map(x => voices.indexOf(x)).join(',');
    const used = voices.filter(x => x.on).length;
    console.log('%c[ELITA]%c note ON  %s (midi %d, key shift %s → %s Hz) → voice #%s  [mode: %s, active voices %d/%d]', C, '', NOTE(n), n, P[9], r3(v[0] ? v[0].freq : 0), vi, ['poly','mono','legato'][P[38]] || P[38], used, POLY);
    if (v[0]) console.log('%c  path%c %s', C2, '', pathString(v[0]));
  }, 0);
}
function pathString(v) {
  const o1 = v.o1, o2 = v.o2, parts = [];
  const uni = o => o.count > 1 ? ' ×' + o.count + ' unison' + (P[93] > UNI_MAX ? ' (clamped from ' + P[93] + ')' : '') : '';
  if (v.g1.gain.value > 0.0001) parts.push(`OSC1(${o1.type}${uni(o1)}, g=${r3(v.g1.gain.value)})`);
  if (v.g2.gain.value > 0.0001) parts.push(`OSC2(${o2.type}${uni(o2)}, g=${r3(v.g2.gain.value)})`);
  if (v.gr.gain.value > 0.0001) parts.push(`RING(OSC1×OSC2, g=${r3(v.gr.gain.value)})`);
  if (v.sg2.gain.value > 0.0001) parts.push(`SYNC-OSC2(worklet, g=${r3(v.sg2.gain.value)})`);
  if (v.gn.gain.value > 0.0001) parts.push(`NOISE(g=${r3(v.gn.gain.value)})`);
  if (v.sg.gain.value > 0.0001) parts.push(`SUB(${v.so.type}, g=${r3(v.sg.gain.value)})`);
  const lf = [], t = ['pitch(osc2)', 'pitch(osc1,2)', 'filter', 'amp', 'p/w', 'FM'];
  [57, 58].forEach((on, k) => { if (P[on]) { const d = P[[41, 46][k]]; lf.push(`LFO${k + 1}→${t[d - 1] || 'none'}`); } });
  const me = P[10] ? ['osc2 pitch', 'FM', 'p/w'][P[71]] : null;
  const f = v.f;
  return [parts.join(' + ') || '(silent: all oscillator levels 0)',
    P[45] > 0 ? `[FM: OSC2→OSC1 pitch, depth ${r3(v.fm.gain.value)} cents]` : '',
    `→ FILTER(${f.type} ${f.rolloff}dB, base ${Math.round(v.fe.baseFrequency)}Hz, Q ${r3(f.Q.value)}, env ${r3(v.fe.octaves)} oct)`,
    v.satWet.gain.value > 0 ? `→ SAT(tanh, drive ×${r3(v.satPre.gain.value * 8)}, wet ${r3(v.satWet.gain.value * 2)})` : '',
    `→ AMP(env A${r3(v.amp.attack)} D${r3(v.amp.decay)} S${r3(v.amp.sustain)} R${r3(v.amp.release)})`,
    lf.length ? `[${lf.join(', ')}]` : '', me ? `[mod env→${me}]` : '',
    '→ voice sum → master → EQ → Chorus → Delay → Pan → Limiter → SoftClip → OUT'].filter(Boolean).join(' ');
}
function chainRows() {
  const on = (b, x) => b ? 'ON' : 'bypass', w = n => r3(n.wet.value);
  return [
    {stage: 'master gain', state: 'ON', detail: `gain ${r3(master.gain.value)} (patch gain #29 × vol)`},
    {stage: 'EQ (peaking)', state: Math.abs(eq.gain.value) > 0.01 ? 'ON' : 'flat', detail: `${Math.round(eq.frequency.value)}Hz, ${r3(eq.gain.value)}dB, Q ${r3(eq.Q.value)}   tone ${r3(toneHi.gain.value)}dB (highs) / ${r3(toneLo.gain.value)}dB (lows)`},
    {stage: 'Chorus 1', state: on(P[66]), detail: `wet ${w(chorus)}, delay ${r3(chorus.delayTime)}ms, depth ${r3(chorus.depth)}, rate ${r3(chorus.frequency.value)}Hz, spread ${chorus.spread}, type x${P[64]}`},
    {stage: 'Chorus 2 (x3/x4 only)', state: on(chorus2.wet.value > 0), detail: `wet ${w(chorus2)}`},
    {stage: 'Delay', state: on(P[65]), detail: `type ${['ST', 'X', 'PP'][delay.type] || delay.type}, wet ${r3(delay.wetAmt)}, time ${r3(delay.time)}s (R ×${r3(delay.dr.delayTime.value / delay.dl.delayTime.value)}), feedback ${r3(delay.fb)}, tone LP ${Math.round(delay.lpL.frequency.value)}Hz`},
    {stage: 'Pan', state: Math.abs(panner.pan.value) > 0.01 ? 'ON' : 'center', detail: `pan ${r3(panner.pan.value)}`},
    {stage: 'Limiter → SoftClip(tanh)', state: 'ON', detail: 'safety'},
    {stage: 'Effect section (#77-81)', state: P[77] ? 'ON (ignored)' : 'off', detail: 'not implemented'},
    {stage: 'Arpeggiator (#59, 31-34)', state: P[59] ? 'ON (ignored)' : 'off', detail: 'not implemented'}
  ];
}
function voiceRows(v, i) {
  return {voice: i, state: v.on ? 'HELD' : (v.amp.value > 0.001 ? 'release' : 'idle'), note: v.note == null ? '' : NOTE(v.note), path: pathString(v)};
}
function lfoRows() {
  return [0, 1].map(k => ({lfo: k + 1, on: !!P[[57, 58][k]], wave: shTimer[k] ? (shTimer[k].ty === 3 ? 'S&H (random steps)' : 'smooth random') : lfos[k].type, 'speed Hz': r3(lfos[k].frequency.value), depth: r3(P[[44, 49][k]]), dest: ['none','osc2 pitch','osc1,2 pitch','filter','amp','p/w','FM','pan (n/a)'][P[[41, 46][k]]] || P[[41, 46][k]]}));
}
function getMeters() {
  if (meters) return meters;
  const tap = n => { const m = new Tone.Meter({smoothing: 0.8}); n.connect(m); return m; };
  meters = {'voice sum (master in)': tap(master), 'after EQ': tap(toneHi), 'after Chorus': tap(chorus2), 'after Delay': tap(delay.output), 'after Pan': tap(panner), 'OUT': tap(clip)};
  voices.forEach((v, i) => { meters['voice' + i + ' filter out'] = tap(v.f); meters['voice' + i + ' amp out'] = tap(v.vg); });
  return meters;
}
window.ELITA.debug = {
  on() { DBG = true; lastP = {}; Object.keys(P).forEach(k => lastP[k] = P[k]); try { sessionStorage.setItem('elita-debug', '1'); } catch (e) {} if (voices) getMeters();
    console.log('%c[ELITA debug ON]%c  graph() voice(i) meters() params() unused()   — notes and parameter changes are logged', C, ''); if (voices) this.graph(); return 'debug on'; },
  off() { DBG = false; try { sessionStorage.removeItem('elita-debug'); } catch (e) {} return 'debug off'; },
  graph() {
    if (!voices) return console.warn('audio not started yet: click the page or press a key first');
    console.group('%c[ELITA] signal path', C);
    console.log('Per voice (6 voices):  [OSC1 | OSC2 | RING | SYNC | NOISE | SUB] → FILTER(+filter env) → AMP(+amp env) → sum');
    console.log('Shared:  voice sum → master → EQ → Chorus1 → Chorus2 → Delay → Pan → Limiter → SoftClip → speakers');
    console.log('Modulation: LFO1/LFO2 (shared, all voices), mod envelope (per voice)');
    console.log('Voices'); console.table(voices.map(voiceRows));
    console.log('Effect chain'); console.table(chainRows());
    console.log('LFOs'); console.table(lfoRows());
    console.groupEnd();
  },
  voice(i = 0) { const v = voices && voices[i]; if (!v) return 'no such voice';
    console.group('%c[ELITA] voice ' + i, C); console.log(pathString(v));
    console.table({osc1: {type: v.o1.type, unison: v.o1.count || 1, gain: r3(v.g1.gain.value), freq: r3(v.o1.frequency.value)},
      osc2: {type: v.o2.type, unison: v.o2.count || 1, gain: r3(v.g2.gain.value), freq: r3(v.o2.frequency.value)},
      sub: {type: v.so.type, unison: 1, gain: r3(v.sg.gain.value), freq: r3(v.so.frequency.value)},
      noise: {gain: r3(v.gn.gain.value)}, ring: {gain: r3(v.gr.gain.value)}, sync: {gain: r3(v.sg2.gain.value)}, fm: {gain: r3(v.fm.gain.value)}});
    console.groupEnd(); },
  meters() { if (!voices) return console.warn('audio not started yet');
    const m = getMeters(); const rows = {};
    Object.keys(m).forEach(k => { const d = m[k].getValue(); rows[k] = {'level dB': r3(typeof d === 'number' ? d : d[0])}; });
    console.table(rows); return 'dB (-Infinity = silent). Play a note first, then run again.'; },
  params() {
    const u = usedSet(), rows = {};
    Object.keys(P).forEach(no => { if (P[no] !== window.ELITA.defaults[no]) rows['#' + no + ' ' + nm(no)] = {value: P[no], default: window.ELITA.defaults[no], 'used by engine': no === 'vol' || u.has(+no) ? 'yes' : 'NO'}; });
    console.table(rows); },
  unused() { const u = usedSet(), un = Object.keys(window.ELITA.defaults).filter(no => no !== 'vol' && !u.has(+no)).map(no => '#' + no + ' ' + nm(no));
    console.log('%c[ELITA]%c parameters on the panel that the engine does not use (%d):\n%s', C, '', un.length, un.join('\n')); return un; },
  get enabled() { return DBG; }
};
{ let q = false; try { q = sessionStorage.getItem('elita-debug') === '1'; } catch (e) {}
  if (/[?&#]debug\b/.test(location.search + location.hash) || q) window.ELITA.debug.on(); }

// ---- hook up to the panel ----
let pending = false, started = null;
function refresh() { if (!voices || pending) return; pending = true; queueMicrotask(() => { pending = false; applyAll(); }); }
async function start() {
  if (!started) started = (async () => { await Tone.start(); await initAudio(); document.body.classList.add('audio-on'); if (DBG) { getMeters(); window.ELITA.debug.graph(); } })();
  return started;
}
window.ELITA.onChange = () => refresh();
{ const b = document.getElementById('bpm');           // tempo box: drives LFO tempo-sync, delay time and the arpeggiator. Whole numbers only (digits, 40..300)
  const set = v => { v = Math.max(40, Math.min(300, parseInt(v, 10) || 120)); BPM = v; if (voices) refresh(); return v; };
  if (b) {
    const clean = s => String(s).normalize('NFKC').replace(/[^0-9]/g, '');
    b.addEventListener('beforeinput', ev => { if (ev.data && !ev.isComposing && clean(ev.data) !== ev.data) ev.preventDefault(); });   // letters, signs and '.' never get in
    b.addEventListener('input', () => { const c = clean(b.value); if (c !== b.value) b.value = c; if (c) set(c); });
    b.addEventListener('blur', () => { b.value = set(b.value || BPM); });                   // empty / out of range -> back to a valid value
    b.addEventListener('keydown', ev => { if (ev.key === 'Enter') b.blur(); else if (ev.key === 'ArrowUp' || ev.key === 'ArrowDown') { ev.preventDefault(); b.value = set((parseInt(b.value, 10) || BPM) + (ev.key === 'ArrowUp' ? 1 : -1) * (ev.shiftKey ? 10 : 1)); } ev.stopPropagation(); });
    b.addEventListener('focus', () => b.select());
  }
  window.ELITA.setBpm = v => { v = set(v); if (b) b.value = v; }; }
window.ELITA.bpm = () => BPM;
window.ELITA.engine = {rawOn: voiceOn, rawOff: voiceOff, lfoHz: () => lfos.map(l => l.frequency.value), start, noteOn, noteOff, allOff, voices: () => voices, wave: () => wave, POLY, used: usedSet, unisonMax: UNI_MAX};
})();
